[project]
name = "possibilistic-portfolio-optimisation-py"
version = "0.1.0"
description = "Possibilistic portfolio optimisation in Python"
requires-python = ">=3.11"

# runtime deps
dependencies = []

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]